ios-xr/xrd-tools

CHANGELOG.md, scripts/host-check, tests/test_host_check.py
Make host-check warn if 2M hugepages are used, regardless of what is supported on the host.
Get rid of checks of what size hugepages are supported on the host.
Corresponding test updates.
=> Warning in host-check if 2M hugepages are used

CHANGELOG.md, scripts/host-check, tests/test_host_check.py
Updates to host-check, including:
- Don't run extra checks by default
- Make igb_uio supported, failing if no PCI driver is loaded, and warning if there's a PCI driver that's installed but not loaded
- Only check if IOMMU is enabled when vfio-pci is being used
- Handle the case where IOMMU is unconfigurable
Plus corresponding updates to test_host_check.py
=> Host check improvements

CHANGELOG.md, scripts/host-check, tests/test_host_check.py
`host-check` script now gives a different error when a command times out
=> Host check Timeout error handling

docs/version-compatibility.md
Subtitle in version-compatibility.md has a stray "XR". Removing that.
=> Fix version compatibility subtitle

CHANGELOG.md, scripts/launch-xrd
With this change all args after -- are passed directly to the container manager.
```
> scripts/launch-xrd -n -p xrd-vrouter --privileged -- foo bar -p xrd-control-plane abcd 
docker run -it --rm --privileged --env XR_MGMT_INTERFACES=linux:eth0,chksum foo bar -p xrd-control-plane abcd
> scripts/launch-xrd -n -p xrd-vrouter -e my_config.cfg --privileged -- foo bar -p xrd-control-plane -e MY_ENV=1 IMG
docker run -it --rm --privileged --mount type=bind,source=/nobackup/yashaga/xrd-tools/my_config.cfg,target=/etc/xrd/every-boot.cfg --env XR_EVERY_BOOT_CONFIG=/etc/xrd/every-boot.cfg --env XR_MGMT_INTERFACES=linux:eth0,chksum foo bar -p xrd-control-plane -e MY_ENV=1 IMG
```
=> -- support in launch-xrd

scripts/xr-compose
Changes to support podman testing with docker-compose.
Set `pids_limit = -1` i.e. set pids limit to unlimited for podman
Use `=`instead of `:` for security-opts since podman only supports `=`
=> Getting podman to work with docker-compose 

scripts/host-check
docker-compose --version has been seen to time out, so increasing the timeout from 5 to 10 seconds.
=> Increase timeout for docker-compose host-check check

CHANGELOG.md, scripts/xr-compose
`xr-compose` to read the input file to check the privilege status of a container. If the field isn't present in the input yaml, CLI arg would be used.
=> XR-compose: Read input file to check container privilege

CHANGELOG.md, scripts/launch-xrd
`launch-xrd` to output a message asking the user to specify the platform when specifying dry-run on a non-loaded image.
The existing behaviour was to try pulling the image. Now it won't try pulling.
```
> scripts/launch-xrd --ctr-client podman-remote3.4 containers.cisco.com/xrd/xrd-vrouter 
Specified image is not loaded, attempting to pull...
Trying to pull containers.cisco.com/xrd/xrd-control-plane:latest...
[...]
> scripts/launch-xrd containers.cisco.com/xrd/xrd-vrouter -n
The image containers.cisco.com/xrd/xrd-vrouter has not been loaded in the local docker registry
Platform must be specified for dry-run when the image isn't loaded
Use '--platform' argument.
> scripts/launch-xrd containers.cisco.com/xrd/xrd-vrouter --platform xrd-vrouter --privileged -n
docker run -it --rm --privileged …
```
=> launch:xrd: Don't try to pull an image, if dry-run is specified

CHANGELOG.md, scripts/host-check, tests/test_host_check.py
The cgroup mounts used by the container needs to exist on the host. If they don't exist, the container manager doesnt clear the stale cgroup rules on stopping the container.
Added a check in `host-check` script to verify the mounts exist.
Manual Tests:
- On Alpine distro (without systemd):
- Ran `host-check` and it fails with the expected error
- On running the suggested command, the cgroup test passed
- On unmounting the memory cgroup, the test failed with the expected error
- On Ubuntu:
- Test passed
Notes:
- If a command is run multiple times in a test, you have to specify it multiple times in `cmd_effects` and `cmd` variable too. Are we okay with that?
- Are the tests I added too much, should I combine/remove any of them?
=> Add if cgroup mounts exists on the host

scripts/launch-xrd
The `CONTAINER_EXE` variable was unquoted in two locations meaning that bash expansion and splitting will be performed. This change quotes the variable.
Before
```
> mkdir my\ dir
> ln -s /bin/docker my\ dir/docker
> launch-xrd --ctr-client "my dir/docker" containers.cisco.com/xrd/xrd-control-plane
Specified image is not loaded, attempting to pull...
Using default tag: latest
latest: Pulling from xrd/xrd-control-plane
Digest: sha256:f3ee6e5df13aeb191834d47f288626b2659fb5199ce28b2ea6203dbad9dfae9e
Status: Image is up to date for containers.cisco.com/xrd/xrd-control-plane:latest
containers.cisco.com/xrd/xrd-control-plane:latest
Image containers.cisco.com/xrd/xrd-control-plane cannot be found in the local docker registry.
```
After
```
> ./scripts/launch-xrd --ctr-client "my dir/docker" …
```
=> launch-xrd: Quote CONTAINER_EXE

scripts/launch-xrd
Skip container manager existence check when --dry-run is specified.
Dry-run shouldn't require the container manager executable existing.
Test - Ran the script with a fake container manager specified.
```
> scripts/launch-xrd  -n -p xrd-control-plane -c docker-foo dummy-image
docker-foo run -it --rm --cap-drop all --cap-add AUDIT_WRITE --cap-add CHOWN --cap-add DAC_OVERRIDE --cap-add FOWNER --cap-add FSETID --cap-add KILL --cap-add MKNOD --cap-add NET_BIND_SERVICE --cap-add NET_RAW --cap-add SETFCAP --cap-add SETGID --cap-add SETUID --cap-add SETPCAP --cap-add SYS_CHROOT --cap-add IPC_LOCK --cap-add NET_ADMIN --cap-add SYS_ADMIN --cap-add SYS_NICE --cap-add SYS_PTRACE --cap-add SYS_RESOURCE --device /dev/fuse --device /dev/net/tun --security-opt apparmor=unconfined --security-opt …
```
=> Skip container manager check when --dry-run is specified

scripts/host-check, scripts/xr-compose
Adding a python version check (> 3.7) to the top of the scripts. This is before the imports because some modules (eg data classes) aren't available on older versions.
Added it to `host-check` and `xr-compose` files.
=> Add python version check to the scripts

.github/pull_request_template.md, .github/workflows/check-release.yml, .github/workflows/release.yml, .github/workflows/sa.yml, .github/workflows/tests.yml, README.md
- Added new GH actions workflow for checking the latest changelog version matches the latest release version, runs once a day.
- Successful run: https://github.com/ios-xr/xrd-tools/actions/runs/5024446124/jobs/9010179057
- Failing run (using new version in changelog): https://github.com/ios-xr/xrd-tools/actions/runs/5024396708/jobs/9010073914
- Updated other GH action workflows to use newer versions of things (e.g. python3.11)
- Added PR template (in use here)
=> Meta: Ensure releases are created for changelog versions

scripts/host-check, tests/test_host_check.py
Seen example 'docker version' output containing "20.10.24+azure-1" (on GH actions ubuntu-latest runner). We should handle this case of the version being 'dirty' (with "+" followed by other stuff).
=> Handle dirty docker version

CHANGELOG.md, commit-check, scripts/host-check, tests/test_host_check.py
Currently, `host-check` warns if unable to perform a check. This can be unclear to users, so add a new `ERROR` case for this.
* Added `CheckState.ERROR`
* Renamed `CheckState.is_error()` method to `CheckState.is_failure()` to distinguish between failure and error cases
* Updated code to use the error check state when checks fail to run
* Updated the output message at the end of the script
* Updated `test_host_check.py`
* Updated `CHANGELOG.md`
`commit-check` script passed without errors.
Code coverage is 98% for `host-check`.
=> CSCwf20183 Update host-check to treat inability to perform a check as an error

CHANGELOG.md, scripts/host-check, tests/test_host_check.py
- Add check in the `host-check` script to verify the kernel modules have been loaded with default runtime parameters.
- In `test_host_check`:
- Add tests to check different configs
- In `perform_check`, if `None` is passed as the file content, then except the file to be read (same as `cmd_effects`)
=> Add kernel modules parameters check

CHANGELOG.md, scripts/host-check, scripts/xr-compose, tests/test_host_check.py
- Add Docker Compose v2 support to scripts `host-check` and `xr-compose`.
- Support both plugin and standalone versions
- Add tests for `host-check` handling both plugin and standalone versions
- Run `host-check` on a host with docker compose plugin
```
> ./host-check -e xr-compose
...
xr-compose checks
-----------------------
PASS -- docker-compose (version 2.18.1)
PASS -- PyYAML (installed)
PASS -- Bridge iptables (disabled)
```
- Testing `xr-compose` on a host with docker compose plugin
```
> xr-compose -f <xr-compose-test.xr.yml> -i <xrd-control-plane-img> -l
[Success]
> docker ps
CONTAINER ID   IMAGE                                      COMMAND            CREATED         STATUS         PORTS     NAMES
c8fc9bf5317a   containers.cisco.com/xrdgen/ubuntu:20.04   "bash"             8 …
```
=> Docker compose v2

CHANGELOG.md, docs/version-compatibility.md, scripts/host-check, tests/test_host_check.py
Updated host-check summary message in the case of some checks failing/error and some checks warning but none failing/erroring.
Also, changed the behaviour of host-check when passed no arguments. Now, a non-zero error code is returned if checks for any platform fail/error/warn.
Tests updated to reflect the new behaviour for checks resulting in warnings and when no platform is specified.
In the case of warnings but no errors get example output:
```
(venv) [ebeaty@sjc-ads-8712 GIT(dev/ebeaty-cisco) xrd-tools]$ scripts/host-check -p xrd-control-plane 
==============================
Platform checks - xrd-control-plane
==============================
PASS -- CPU architecture (x86_64)
PASS -- CPU cores (16)
PASS -- Kernel version (4.18)
PASS -- Base kernel modules[...]
PASS -- Cgroups (v1)
WARN …
```
=> Update host-check rc and summary string for case of no errors/failures but warnings

CHANGELOG.md, scripts/host-check, tests/test_host_check.py
`host-check` checks that there are PCI devices available in the IOMMU check, but IOMMU is only relevant for `vfio-pci`, not `igb_uio`. Should separate the checks for PCI devices from the IOMMU check.
New check setup:
* `check_iommu()`: keeps existing checks for IOMMU but no longer looks for PCI devices.
* `check_pci_devices()`:
*  If IOMMU is enabled, checks that IOMMU PCI devices are available.
*  If IOMMU is not enabled, checks that any PCI devices are available.
Testing: existing tests for IOMMU split between new IOMMU and PCI devices checks. 
=> Separate IOMMU and PCI device checks.

CHANGELOG.md, Dockerfile.host-check, pyproject.toml, scripts/host-check
Incorrect entry-point in host-check. 
Tested manually using `podman run` and the Helm chart.
=> Fix issue in entry-point in host-check dockerfile

CHANGELOG.md, scripts/host-check, tests/test_host_check.py
Update host-check with AWS-specific checks. AWS checks are run if OS is Amazon Linux.
Changes:
* Cgroups: now pass for both v1 and v2 everywhere
* Kernel driver: fail if igb_uio is not present when in AWS
* IOMMU: pass instead of warn when in AWS
* Added check of boot cmdline args that checks they match those we set in xrd-packer. This also checks that there are at least 2 isolated CPUs.
Note that the sysctls we set are already tested in host-check but those that tuned sets for us are not. I have not added a test for this as I don't believe we have as strong an opinion about them/have not justified these settings ourselves.
UT written, gives full coverage of changes.
```
$ ./test.py 
==============================
Platform checks
==============================
base checks …
```
=> Add custom behaviour if OS is Amazon Linux

CHANGELOG.md, scripts/apply-bugfixes
Update help string for apply-bugfixes to explain what the SOURCE argument is and give some examples
Updated output:
```
$ scripts/apply-bugfixes -h
Usage: apply-bugfixes [-h|--help] [--new-packages] IMAGE SOURCE ...
Create a new XRd image with bugfixes installed on top of a base image.
Required arguments:
IMAGE            Loaded container image to install bugfixes on top of
SOURCE           Path to source to install packages from - a directory
or tarball containing the rpm(s) to install.
Optional arguments:
--new-packages   Install new packages if included in the bugfix source. By
default, only packages that are already installed in the
base image will be updated, so this should be passed if
any new packages are present in SOURCE.
...              Additional args passed through to 'docker …
```
=> Apply bugfix source help
